fontInfo = {
    "fontFamily": "Yu Gothic UI",
}
textList = {
    "defaultFont": (fontInfo["fontFamily"], 9),
    "font2": (fontInfo["fontFamily"], 14),
    "font3": (fontInfo["fontFamily"], 15),
    "font4": (fontInfo["fontFamily"], 13),
    "font5": (fontInfo["fontFamily"], 20),
    "font6": (fontInfo["fontFamily"], 16),
    "font7": (fontInfo["fontFamily"], 11),
    "comicscript": {
        "fileType": "COMIC_SCRIPT",
        "cmdLabel": "Command Name",
        "paramLabel": "Number of Parameters",
        "posLabel": "Insert Position",
        "paramNumLabel": "param{0}",
        "posValue": ["After", "Before"],
        "imgInfo": "Image Info",
        "imgSizeInfo": "Image Size Info",
        "seInfo": "SE Info",
        "bgmInfo": "BGM Info",
        "noList": "(None)",
        "pasteFront": "Before",
        "pasteBack": "After",
        "pasteCancel": "Cancel",
        "headerModify": "Modify Header Info",
        "headerInsert": "Insert Header Info",
        "headerImgLabel": "Image File Name",
        "headerImgIndex": "Image File\nINDEX",
        "headerImgX": "X Coordinate",
        "headerImgY": "Y Coordinate",
        "headerImgWidth": "Width",
        "headerImgHeight": "Height",
        "headerSELabel": "SE File",
        "headerSEGroup": "Group Count",
        "headerBGMLabel": "BGM File",
        "headerBGMLoopFlag": "BGM Loop Flag",
        "headerBGMStart": "BGM Start Position",
        "headerBGMLoopStart": "BGM Loop Start Position",
        "headerBGMLoopLabelInfo": ["No Loop", "Loop"],
        "treeNum": "No.",
        "treeName": "Command Name",
        "cmdModify": "Modify Command",
        "cmdInsert": "Insert Command",
        "cmdPaste": "Copy Command",
        "headerInfo": "Header Info",
        "selectNum": "Selected Row Number: ",
        "editLineLabel": "Modify Selected Row",
        "insertLineLabel": "Insert at Selected Row",
        "deleteLineLabel": "Delete Selected Row",
        "copyLineLabel": "Copy Selected Row",
        "pasteLineLabel": "Paste at Selected Row",
        "headerEditLabel": "Modify Header Info",
        "csvExtractLabel": "Extract as CSV",
        "csvSaveLabel": "Overwrite from CSV",
        "scriptLabel": "Script Contents",
        "commonModifyLabel": " Change",
        "commonInsertLabel": " Insert",
    },
    "fvtMaker": {
        "fileType": "CSV File",
        "fvtNum": "FVT\nNo.",
        "faceNum": "FACE\nNo.",
        "faceWidth": "FACE\nWidth",
        "faceHeight": "FACE\nHeight",
        "faceX": "FACE\nX Coordinate",
        "faceY": "FACE\nY Coordinate",
        "effect": "Effect",
        "voNum": "VO\nNo.",
        "text": "Text",
        "faceNum2": "FACE No.",
        "faceNumDesc": "Specify the FACE image file number.\nSpecify 0 for no image",
        "faceSize": "FACE Size",
        "faceSizeDesc": "See the diagram on the right for the cropping method.\nDefault is [-1,-1,-1,-1]",
        "effectDesc": "0 (Normal [follows game speed])\
            \n1 (Shake [follows game speed])\
            \n2 (Rises from below [LS only])\
            \n3 (Image positioned lower [follows game speed])\
            \n4 (Shake)\
            \n5 (Image positioned lower)\
            \n6 (Appears from center of screen [LS only])\
            \n7 (Normal)",
        "voNum2": "VO No.",
        "voNumDesc": "Specify the VO voice file number.\nSpecify 0 for no voice",
        "textTag": "Text\nTags",
        "textTagDesc": "<BR>, <PAGE>, <WAIT120>\n<FC#255016000></FC>, and so on...",
        "csvLfLabel": "CSV Format (the first row of the CSV is treated as a header and skipped when loading)",
        "howWrite": "How to Create",
    },
    "mdlBin": {
        "fileType": "MODEL_SCRIPT",
        "cmdLabel": "Command Name",
        "paramLabel": "Number of Parameters",
        "posLabel": "Insert Position",
        "paramNumLabel": "param{0}",
        "posValue": ["After", "Before"],
        "treeNum": "No.",
        "treeDelay": "delay",
        "treeName": "Command Name",
        "treeFileFlag": "File Flag",
        "treeSection": "Section",
        "cmdModify": "Modify Command",
        "cmdInsert": "Insert Command",
        "cmdPaste": "Copy Command",
        "pasteFront": "Before",
        "pasteBack": "After",
        "pasteCancel": "Cancel",
        "headerModify": "Modify Header Info",
        "headerInsert": "Insert Header Info",
        "imgInfo": "Image Info",
        "imgSizeInfo": "Image Size Info",
        "smfInfo": "SMF Info",
        "seInfo": "SE Info",
        "tgaInfo": "TGA Info",
        "noList": "(None)",
        "headerInfo": "Header Info",
        "headerImgLabel": "Image File Name",
        "else": "Element",
        "headerElse1Value": [0, 1],
        "headerImgIndex": "Image File\nINDEX",
        "headerImgX": "X Coordinate",
        "headerImgY": "Y Coordinate",
        "headerImgWidth": "Width",
        "headerImgHeight": "Height",
        "headerSmfLabel": "SMF File Name",
        "headerSELabel": "SE File",
        "headerSEGroup": "Group Count",
        "headerTgaLabel": "TGA File Name",
        "headerTgaB": "B",
        "headerTgaPer": "per",
        "listNumModifyLabel": "Change Number of Sections",
        "listHeaderModifyLabel": "Change Section Contents",
        "numModifyLabel": "Change List Count",
        "selectNum": "Selected Row Number: ",
        "editLineLabel": "Modify Selected Row",
        "insertLineLabel": "Insert at Selected Row",
        "deleteLineLabel": "Delete Selected Row",
        "copyLineLabel": "Copy Selected Row",
        "pasteLineLabel": "Paste at Selected Row",
        "headerEditLabel": "Modify Header Info",
        "listNumModifyBtnLabel": "Modify Number of Sections",
        "listHeaderModifyBtnLabel": "Modify Section Contents",
        "numModifyBtnLabel": "Modify List Count",
        "csvExtractLabel": "Extract as CSV",
        "csvSaveLabel": "Overwrite from CSV",
        "scriptLabel": "Script Contents",
        "anime1Label": "ANIME_1",
        "anime2Label": "ANIME_2",
        "commonModifyLabel": " Change",
        "commonInsertLabel": " Insert",
    },
    "mdlinfo": {
        "fileType": "MDLINFO",
        "mdlinfoLf": "Model Detail Info",
        "selectNum": "Selected Row Number: ",
        "searchModel": "Search Model: ",
        "scriptLabel": "MDLINFO Contents",
        "posLabel": "Insert Position",
        "pos1": "After No.{0}",
        "pos2": "Before No.{0}",
        "pos3": "After Last",
        "posSplit": " ",
        "posLast": "Last",
        "pos4": "After",
        "pos5": "Before",
        "pasteFront": "Before",
        "pasteBack": "After",
        "pasteCancel": "Cancel",
        "treeNum": "No.",
        "treeSmf": "smf",
        "treeSmfType": "Type",
        "treeSmfEleNum": "Number of smf Elements",
        "treeColorNum": "Number of Colors",
        "treeMesh": "mesh",
        "treeConst": "const",
        "treeEle1-3": "ele1-3",
        "treeDiff": "DIFF",
        "treeEmis": "EMIS",
        "treeNum2": "num",
        "editColorLabel": "Modify Color Info",
        "elementModifyLabel": "Modify Detail Elements",
        "elementInsertLabel": "Insert Detail Elements",
        "elementDeleteLabel": "Delete Detail Elements",
        "allElementModifyLabel": "Modify Detail Elements by Mesh",
        "texImageLabel": "Modify Image",
        "detailModelLabel": "Modify Model Elements",
        "detailModelInfo": "Model Detail Info",
        "detailModelTypeInfo": "Model Type Info",
        "imageListLabel": "Image List",
        "smfTypeLabel": "Type",
        "detailModelMeshLabel": "Mesh No",
        "detailModelMtrlLabel": "Mtrl No",
        "detailModelEleNum": "ele{0}",
        "copyAnotherMdlinfo": "Copy from Another MDLINFO",
        "copyModelLabel": "Copy MDLINFO Info",
        "smfInfo": "smf Element Info",
        "smfName": "Name",
        "smfParam": "param",
        "smfInfoModify": "Modify smf Element",
        "smfInfoInsert": "Insert smf Element",
        "smfInfoDelete": "Delete smf Element",
        "smfElementModify": "Modify smf Element",
        "smfElementInsert": "Insert smf Element",
        "binFileOrFlagLabel": "Binary File and Flag Info",
        "smfNameLabel": "smf Name",
        "binFileLabel": "bin File",
        "binFileFlag": "Flag",
        "mdlDetailLabel": "Selected Model's Detail Info",
        "mdlTypeLabel": "Selected Model's Type Info",
        "mdlSmfEleLabel": "Selected Model's smf Element Info",
        "binFileFlagLabel": "Modify bin File and Flag",
        "copyAnotherMdlinfoLabel": "Copy from Another MDLINFO",
        "mdlinfoDeleteLabel": "Delete Selected Model Info",
        "mdlinfoCopyLabel": "Copy Selected Row",
        "mdlinfoPasteLabel": "Paste at Selected Row",
        "addSmfModelLabel": "Add Model with SMF Info",
        "noList": "(None)",
        "posValue": ["After", "Before"],
    },
    "musicEditor": {
        "fileType": "MUSIC_DATA",
        "bsTitle": "BGM List (1.07 base)",
        "csTitle": "BGM List (1.06 base)",
        "rsTitle": "BGM List (1.08 base)",
        "bgmNo": "No",
        "bgmFilename": "BGM File Name",
        "bgmName": "BGM Name",
        "commonTitle": [
            "start",
            "loop start",
            "loop end"
        ],
        "changeBgmNum": "BGM Number to Change",
        "bgmModify": "Modify BGM",
        "bgmSwap": "Swap BGM",
        "bgmModifyLabel": "Modify This BGM",
        "bgmSwapLabel": "Swap This BGM",
        "scriptLabel": "BGM List",
    },
    "orgInfoEditor": {
        "fileType": "TRAIN_DATA",
        "noUsed": "(Unused)",
        "unknown": "Unknown",
        "noList": "None",
        "notchLabel": "Notch",
        "perfLabel": "Performance",
        "csvNotchSpeed": "speed",
        "csvNotchTlk": "tlk",
        "csvNotchSound": "sound",
        "csvNotchAdd": "add",
        "csvDaishaTitle": "Bogie Model",
        "csvOrgNumTitle": "Number of Train Sets",
        "csvMdlTitle": "Car Model",
        "csvMdlIdxTitle": "Car Index",
        "csvColTitle": "COL Model",
        "csvColIdxTitle": "COL Index",
        "csvPantaTitle": "Pantograph Model",
        "csvPantaIdxTitle": "Pantograph Index",
        "csvElseTitle": "Attribute Index",
        "csvLensTitle": "Lens Flare",
        "csvTailTitle": "Tail Lamp",
        "csvModelIdx2Title": "Model Index 2",
        "colorCnt": "Number of Colors",
        "csvColorIdx": "Color {0},",
        "csvModelIdx": "Model {0},{1}\n",
        "csvColorModelIdx": "Color {0}, Model {1}",
        "hurikoCnt": "Number of Tilt Stages",
        "hurikoRange": "Tilt Bend Angle (°)",
        "rainAdd": "Rain Acceleration",
        "rainBreake": "Rain Braking Force",
        "rainHill": "Rain Uphill",
        "rainDown": "Rain Downhill",
        "trackOutPer": "Derailment Setting Coefficient",
        "trackKntPer": "Cant Coefficient",
        "breakeOutPow": "Reduce Derailment Value Rise When Braking",
        "maxOutParam": "Max Derailment Value per Frame",
        "hurikoCntSS": "Number of Tilts",
        "hurikoAngleSS": "Tilt Angle",
        "trackCnt": "Number of Bogies per Car",
        "readTrackNum": "Number of Bogies to Read",
        "trackName": "TrackName",
        "trackMdlName": "Standard Gauge Model",
        "lowTrackMdlName": "Narrow Gauge Model",
        "hurikoPow": "Tilt Reduction Value",
        "oneWheelPow": "One-Wheel Running Rise Rate",
        "oneWheelTime": "One-Wheel Running Duration",
        "oneWheelAfterTime": "Time Until Fall After One-Wheel Running Duration",
        "trackComboList": ["Standard Gauge", "Narrow Gauge"],
        "stage1PLabel": "1P",
        "stage2PLabel": "2P",
        "stage3PLabel": "3P",
        "stageTrackName": "Bogie",
        "stageNumLabel": "Stage {0}",
        "extractCsv": "Extract Train Info as CSV",
        "extractText": "Extract Train Info as Text",
        "saveCsv": "Overwrite Train Info from CSV",
        "saveText": "Overwrite Train Info from Text",
        "trainModify": "Modify This Train",
        "trainSave": "Save",
        "allSave": "Modify All at Same Rate",
        "allSaveLabel": "Batch Modify All Trains' Performance",
        "speedLfLabel": "Speed",
        "perfLfLabel": "Performance",
        "trainLfLabel": "Train",
        "orgModify": "Modify This Train Set",
        "modelInfoModify": "Modify Model Info",
        "SSTrainLfLabel": "Train",
        "SSRainLfLabel": "Rain",
        "SSCarbLfLabel": "Curve",
        "SSOtherLfLabel": "Other",
        "SSHurikoLfLabel": "Tilt",
        "SSOneWheelLfLabel": "One-Wheel Running",
        "noPerf": "-",
        "modifyBtnLabel": "Modify",
        "valueModify": "Change Value",
        "defaultValueLabel": "Default Value = ",
        "setDefaultBtnLabel": "Reset Train Performance to Default",
        "setDefaultLabel": " to Default",
        "setDeleteLabel": "(Delete)",
        "perfElement": "Element",
        "perfAllTrainLabel": " All",
        "perfCalcList": ["Multiply by", "Set to"],
        "editNotchLabel": "Modify Notch Info",
        "editNotchList": ["4 Notch", "5 Notch", "12 Notch"],
        "calcMinSpeedLabel": "{0} -> Minimum speed to reach {1} notch",
        "SSElsePerfModifyBtn": "Modify",
        "SSElsePerfModifyLabel": "Modify {0} Info",
        "useThisPerfLabel": "Use This Performance",
        "fixedListNumLabel": "No.{0}",
        "fixedList2ModifyLabel": "Change else",
        "fixedList2NumLabel": "num",
        "fixedList2NameLabel": "name",
        "modelTrainLabel": "Car",
        "modelModelLabel": "Model",
        "modelPantaLabel": "Pantograph",
        "modelColLabel": "COL",
        "editModelLabel": "Modify Model Info",
        "lensInfoLabel": "Lens Flare Info",
        "lensCntLabel": "Number of Lens Entries",
        "lensNameLabel": "name",
        "lensF1Label": "f1",
        "lensB1Label": "b1",
        "lensEditCntLabel": "Change Number of Lens Entries",
        "lensEditLabel": "Change Lens Info",
        "lensInfoLabelList": [
            "name1",
            "name2",
            "f1",
            "f2",
            "b1",
            "b2",
            "b3",
            "b4",
        ],
        "tailInfoLabel": "Tail Info",
        "tailCntLabel": "Number of Tail Entries",
        "tailNameLabel": "name",
        "tailElseLabel": "else",
        "tailF1Label": "f1",
        "tailB1Label": "b1",
        "tailEditCntLabel": "Change Number of Tail Entries",
        "tailEditLabel": "Change Tail Info",
        "tailSmfNameLabel": "name{0}",
        "tailSmfElseLabel": "else{0}",
        "menuComboValues": ["Speed/Performance Info", "Count/Model Info", "Lens Flare Info"],
        "menuComboSSValues": ["Speed/Performance Info", "Count/Other Info"],
        "editStageLabel": "Modify Stage Info",
        "modified": "(Modified)",
        "dataCorrupted": "(Data Corrupted)",
        "editStageDefaultTrain": "Change Stage Default Train",
        "commonModifyLabel": " Change",
        "commonInsertLabel": " Insert",
        "posLabel": "Insert Position",
        "posValue": ["After", "Before"],
        "lsStageLabelList": [
            "Episode 1",
            "Episode Plus",
            "Episode 2",
            "Episode 3",
            "Episode 4",
            "Taku-chan",
            "Compilation"
        ]
    },
    "railEditor": {
        "fileType": "Rail Data",
        "railDataExtractExcel": "Extract Rail Data as Excel",
        "railDataSaveExcel": "Overwrite Rail Data from Excel",
        "initPos": "Initial Placement",
        "dummyPos": "Dummy Placement?",
        "pracOrVsPos": "Practice/2-Player Battle Placement",
        "lightInfo": "Light Info",
        "stationInfo": "Station Sign Image Info",
        "baseBinInfo": "Base bin Info",
        "bgmNum": "Number of BGMs",
        "modifyBtnLabel": "Modify",
        "editBgmNumLabel": "Change Number of BGMs",
        "editBgmListLabel": "Change BGM List",
        "noList": "(None)",
        "modifyBgmLabel": "Change BGM",
        "insertBgmLabel": "Insert BGM",
        "editBgmInfoLabelList": ["File Name", "BGM Name", "start", "loopStart"],
        "posLabel": "Insert Position",
        "posValue": ["After", "Before"],
        "railPosPlayerLabel": "player",
        "railPosRailNoLabel": "railNo",
        "railPosRailPosLabel": "railPos",
        "railPosB1Label": "b1",
        "railPosF1Label": "f1",
        "railPosPlayerNameLabel": "{0}P",
        "commonModifyLabel": " Change",
        "commonInsertLabel": " Insert",
        "editRailPosLabelList": ["railNo", "railPos", "b1", "f1"],
        "trainCount": "Number of Cars",
        "editTrainCountLabel": "Change Number of Cars",
        "stationNo": "Initial Station Display No",
        "editStationNoLabel": "Change Initial Station Display No",
        "editBaseBinAnimeLabel": "Base bin ANIME",
        "animeCntLabel": "Number of ANIME",
        "editAnimeCntLabel": "Change Number of ANIME",
        "editAnimeInfoLabel": "Change ANIME Info",
        "editBinAnimeHeaderList": ["const1", "param1", "param2"],
        "else1Label": "else1",
        "editElse1Label": "Change else1",
        "editElse1F1Label": "f{0}",
        "editElse1B1Label": "b{0}",
        "editValueLabel": "Value",
        "stationInfoLabel": "Station Sign AMB Info",
        "stationInfoCntLabel": "Number of Station Sign AMBs",
        "stationConst0Label": "const0",
        "stationAmbNoLabel": "AMB Number",
        "stationAmbChildNoLabel": "AMB Child Number",
        "stationElementLabel": "ele",
        "stationImgNoLabel": "Image Number",
        "editStationCntLabel": "Change Number of Station Signs",
        "editStationInfoLabel": "Change Station Sign AMB Info",
        "editStationInfoLabelList": ["const0", "AMB Number", "AMB Child Number", "ele", "Image Number"],
        "smfInfoLabel": "smf Info",
        "selectNum": "Selected Row Number: ",
        "usedRail": "Rail",
        "usedAmb": "AMB",
        "commonEditLineLabel": "Modify Selected Row",
        "commonInsertLineLabel": "Insert at Selected Row",
        "commonDeleteLineLabel": "Delete Selected Row",
        "commonCopyLineLabel": "Copy Selected Row",
        "commonPasteLineLabel": "Paste at Selected Row",
        "editSmfElementListLabel": "Modify Selected Row's List",
        "smfInfoNum": "No.",
        "smfInfoName": "smf Name",
        "smfInfoFlag1": "Flag 1",
        "smfInfoFlag2": "Flag 2",
        "smfInfoLength": "Length",
        "smfInfoMesh1": "Mesh Display 1",
        "smfInfoMesh2": "Mesh Display 2",
        "smfInfoKasenchuNo": "Overhead Wire Pole No",
        "smfInfoKasenNo": "Overhead Wire No",
        "smfInfoElementList": "List Count",
        "smfInfoE1": "e1",
        "modifySmfInfo": "Modify smf",
        "insertSmfInfo": "Insert smf",
        "pasteSmfInfo": "Paste smf",
        "editSmfElementList": "Change List",
        "modelFlagList": [
            ["Rail", "Overhead Wire Pole", "Overhead Wire", "Bone Background Object", "Crossing Sound", "Bridge Passing Sound", "Slab Track Sound", "Snow Accumulates"],
            ["Exclude from Drift Search", "Flag 2", "Flag 3", "Flag 4", "Launch on One-Wheel Drift", "Launch on Left-Side One-Wheel Drift", "Launch on Right-Side One-Wheel Drift", "Launch on Drift"],
        ],
        "setSmfSwitch": "Switch Setting",
        "pasteFront": "Before",
        "pasteBack": "After",
        "pasteCancel": "Cancel",
        "modifySmfElementListLabel": "Change List",
        "insertSmfElementListLabel": "Insert List",
        "smfElementListLabel1": ["e1", "e2", "e3"],
        "smfElementListLabel2": ["e1", "e2"],
        "stationNameLabel": "Station Name Position Info",
        "stationNameNum": "No.",
        "stationNameName": "Station Name",
        "stationNameFlag": "Station Flag",
        "stationNameRailNo": "Rail No",
        "stationNameF1": "f1",
        "stationNameF2": "f2",
        "stationNameF3": "f3",
        "stationNameE1": "e1",
        "stationNameE2": "e2",
        "stationNameE3": "e3",
        "stationNameE4": "e4",
        "stationNameF4": "f4",
        "stationNameF5": "f5",
        "stationNameF6": "f6",
        "modifyStationNameLabel": "Modify Station Name Position",
        "insertStationNameLabel": "Insert Station Name Position",
        "pasteStationNameLabel": "Paste Station Name Position",
        "else2InfoLabel": "else2",
        "else2CntLabel": "Number of else2",
        "modifyElse2CntLabel": "Change Number of else2",
        "modifyElse2InfoLabel": "Change else2",
        "editElse2LabelList": ["e1", "e2", "f1", "f2", "f3", "e3"],
        "cpuInfoLabel": "CPU Info",
        "cpuInfoNum": "No.",
        "cpuInfoRailNo": "Rail No",
        "cpuInfoConst1": "const1",
        "cpuInfoMode": "mode",
        "cpuInfoMinLen": "minLen",
        "cpuInfoMaxLen": "maxLen",
        "cpuInfoMaxSpeed": "maxSpeed",
        "cpuInfoMinSpeed": "minSpeed",
        "cpuInfoList": "list1",
        "cpuInfoDefSpeed": "defSpeed",
        "cpuInfoList2": "list2",
        "modifyCpuInfoLabel": "Modify CPU Info",
        "insertCpuInfoLabel": "Insert CPU Info",
        "pasteCpuInfoLabel": "Paste CPU Info",
        "cpuInfoLsListLabel": "list{0}-{1}",
        "comicScriptLabel": "Comic Script",
        "modifyComicScriptLabel": "Change Comic Script",
        "insertComicScriptLabel": "Insert Comic Script",
        "editComicScriptLabelList": ["Script No", "Event Type", "Rail No"],
        "editLsComicScriptFLabel": "f{0}",
        "dosansenInfoLabel": "Dosan Line Info",
        "dosansenCntLabel": "Number of Dosan Line Entries",
        "dosansenStart": "Start",
        "dosansenEnd": "Landing",
        "dosansenE1": "e1",
        "dosansenAnime": "anime",
        "dosansenE2": "e2",
        "dosansenF1": "f1",
        "editDosansenCntLabel": "Change Number of Dosan Line Entries",
        "editDosansenInfoLabel": "Change Number of Dosan Line Entries",
        "editDosansenLabelList": [
            "Start Rail No",
            "Start Rail Pos (from)",
            "Start Rail Pos (to)",
            "Landing Rail No",
            "Landing Rail Pos (from)",
            "Landing Rail Pos (to)",
            "e1",
            "anime_f1",
            "anime_f2",
            "anime_f3",
            "anime_f4",
            "e2",
            "f1"
        ],
        "smfListAddList1": ["None", "As Set on Model"],
        "smfListAddList2": ["None"],
        "railRailNo": "Rail No",
        "railSearchBtnLabel": "Look Up",
        "railCsvExtractLabel": "Extract as CSV",
        "railCsvSaveLabel": "Overwrite from CSV",
        "railCsToRs": "Create RS Port File",
        "railBlockInfo": "Block Info",
        "railPrevRailNo": "Rail No to Connect",
        "railBlockNo": "Block No",
        "railXyzInfo": "Direction XYZ Info",
        "railDirX": "X Direction",
        "railDirY": "Y Direction",
        "railDirZ": "Z Direction",
        "railModelKasenInfo": "Model/Overhead Wire Info",
        "railModelLabel": "Model (smf)",
        "railKasenNoLabel": "Overhead Wire",
        "railKasenLabel": "Overhead Wire (smf)",
        "railKasenchuLabel": "Overhead Wire Pole (smf)",
        "railPer": "per",
        "railLsVer0101": "VER0101 Info",
        "railPrevRail2No": "Rail No to\nConnect (2)",
        "railPosXyzInfo": "XYZ Info",
        "railPosX": "X Pos",
        "railPosY": "Y Pos",
        "railPosZ": "Z Pos",
        "railRotXyzInfo": "XYZ Rotation Info",
        "railRotX": "X Rotation",
        "railRotY": "Y Rotation",
        "railRotZ": "Z Rotation",
        "railFixAmbLabel": "Fixed AMB (smf)",
        "railFlagInfo": "Flag Info",
        "railFlagInfoList": [
            [
                "Sound While\nCrossing Passes",
                "Launch on\nDouble-Track Drift",
                "180-Degree Turn\nat Near Position",
                "LAST_POS",
                "LAST01",
                "LAST00",
                "Sound While\nBridge Passes",
                "No Drift"
            ],
            [
                "Raise Camera\nPosition on Crash",
                "Other Rails Also\nDrift Targets",
                "Long Car Bodies\nHit Walls Except\nOn Double-Track\nDrift",
                "Less Speed Loss\nOn Derailment",
                "CPU Tilt Train\nTilt Only",
                "CPU One-Wheel\nDrift Recovery",
                "CPU Right\nOne-Wheel Drift",
                "CPU Left\nOne-Wheel Drift"
            ],
            [
                "Launch on\nOne-Wheel Drift",
                "Launch on Right-Side\nOne-Wheel Drift",
                "Launch on Left-Side\nOne-Wheel Drift",
                "Rail Hidden",
                "Dosan Line on\nLeft Input",
                "Dosan Line on\nRight Input",
                "Rail Guard\non Right",
                "Rail Guard\non Left"
            ],
            [
                "Disabled\nRail",
                "CPU\nTrack Switch",
                "L_RUN",
                "R_RUN",
                "Flag 5",
                "CPU Drift\nRecovery",
                "CPU\nRight Drift",
                "CPU\nLeft Drift"
            ]
        ],
        "railOldFlag1": "Instant Jump\nWhen Pressed",
        "railOldFlag2": "Driver View\nShakes",
        "railOldFlag3": "Trolley Wire",
        "railOldFlag4": "Low-Speed Track",
        "railRailInfo": "Rail Info",
        "railRailDataCnt": "Number of Rails",
        "railCreateRevRail": "Create Return Rail",
        "railNextRail": "Next Rail",
        "railPrevRail": "Previous Rail",
        "railRevNextRail": "Next Rail (rev)",
        "railRevPrevRail": "Previous Rail (rev)",
        "railCsvFileType": "Rail Data CSV",
        "railCsToRsBinType": "RS Port BIN",
        "else3Label": "else3",
        "camLabel": "Cam",
        "else3Num": "No.",
        "editElse3InfoListLabel": "Modify Selected Row's List",
        "editElse3Label": "Change {0}",
        "insertElse3Label": "Insert {0}",
        "pasteElse3InfoLabel": "Paste {0} Info",
        "editElse3LabelList": ["Rail No", "Count"],
        "editElse3LsLabelList": ["f1", "f2", "f3", "Count"],
        "editElse3ElementLabel": "{0} List Info",
        "editElse3ElementLabelList": ["Type", "railPos", "bin index", "anime1", "anime2"],
        "editElse3LsElementLabelList": ["f1", "f2", "f3", "f4", "b1"],
        "editElse3ElementModifyLabel": "Change {0} List Info",
        "editElse3ElementInsertLabel": "Insert {0} List Info",
        "else3ExtractCsvLabel": "Extract as CSV",
        "else3LoadAndSaveCsvLabel": "Overwrite from CSV",
        "else4Label": "else4",
        "else4CntLabel": "Number of else4",
        "editElse4CntLabel": "Change Number of else4",
        "editElse4Label": "Change else4",
        "editElse4ElementLabelList": ["railNo", "prevRail", "pos_x", "pos_y", "pos_z", "rot_x", "rot_y", "rot_z"],
        "ambAmbNo": "AMB No",
        "ambSearchBtnLabel": "Look Up",
        "ambCsvExtractLabel": "Extract as CSV",
        "ambCsvSaveLabel": "Overwrite from CSV",
        "ambInfoLabel": "AMB Info",
        "ambType": "Type",
        "ambLength": "Length",
        "ambRailNo": "Placement Rail No",
        "ambRailPos": "Placement Rail Pos",
        "ambPosDirInfo": "BASE Distance/Direction XYZ Info",
        "ambBasePosX": "X Distance",
        "ambBasePosY": "Y Distance",
        "ambBasePosZ": "Z Distance",
        "ambBaseDirX": "X Direction",
        "ambBaseDirY": "Y Direction",
        "ambBaseDirZ": "Z Direction",
        "ambInfo2Label": "AMB Info 2",
        "ambPriority": "Priority",
        "ambFog": "Fog",
        "ambLsPos": "Type",
        "ambLsModel": "AMB Model (smf)",
        "ambLsAnime": "ANIME Number",
        "ambModelInfo": "AMB Model Info",
        "ambChildModelInfo": "AMB Child Model Info",
        "ambModelSmf": "Model (smf)",
        "ambChildModelSmf": "Child Model (smf)[{0}]",
        "ambModelPosX": "X Distance",
        "ambModelPosY": "Y Distance",
        "ambModelPosZ": "Z Distance",
        "ambModelDirX": "X Direction",
        "ambModelDirY": "Y Direction",
        "ambModelDirZ": "Z Direction",
        "ambModelRotX": "X-Axis Rotation",
        "ambModelRotY": "Y-Axis Rotation",
        "ambModelRotZ": "Z-Axis Rotation",
        "ambModelPer": "per",
        "ambModelBsSmf": "Model (smf)",
        "ambModelBsDetail": "Pawn Count",
        "ambCsvFileType": "AMB Data CSV",
        "railComboValue": [
            "BGM/Placement Info",
            "Element 1",
            "smf Info",
            "Station Name Position Info",
            "Element 2",
            "CPU Info",
            "Comic Script/Dosan Line",
            "Rail Info",
            "Element 3",
            "Element 4",
            "AMB Info"
        ],
        "railLsComboValue": [
            "BGM/Placement Info",
            "Element 1",
            "smf Info",
            "Station Name Position Info",
            "Element 2",
            "CPU Info",
            "Comic Script/Dosan Line",
            "Rail Info",
            "Cam",
            "Element 4",
            "AMB Info"
        ],
        "configReadFail": "Failed to read config!",
        "printModelName": {
            0: "Model: Model names will be read by name",
            1: "Model: Model names will be read by index"
        },
        "printFlagHexMode": {
            0: "Flag: Flags will be read as decimal",
            1: "Flag: Flags will be read as hexadecimal"
        },
        "printAmbReadMode": {
            0: "AMB: Read as line-broken AMB info",
            1: "AMB: Read as single-line AMB info"
        }
    },
    "rsRail": {
        "1pRailPos": "1P's Lead Car Bogie Position",
        "2pRailPos": "Opponent's Lead Car Bogie Position",
        "trainPosSearchBtnLabel": "Start Tracking",
        "railNo": "Rail No",
        "railSearchBtnLabel": "Look Up",
        "railChangeBtnLabel": "Change",
        "railXyzInfo": "Direction XYZ Info",
        "railDirX": "X Direction",
        "railDirY": "Y Direction",
        "railDirZ": "Z Direction",
        "railModelPer": "Model PER",
        "railPer": "per",
        "ambNo": "AMB No",
        "ambSearchBtnLabel": "Look Up",
        "ambChangeBtnLabel": "Change",
        "ambRecreateTime": "AMB Redraw Time (seconds)",
        "ambInfoLabel": "AMB Info",
        "ambLength": "Length",
        "ambRailNo": "Placement Rail No",
        "ambRailPos": "Offset",
        "ambPosDirInfo": "BASE Distance/Direction XYZ Info",
        "ambBasePosX": "X Distance",
        "ambBasePosY": "Y Distance",
        "ambBasePosZ": "Z Distance",
        "ambBaseRotX": "X Rotation",
        "ambBaseRotY": "Y Rotation",
        "ambBaseRotZ": "Z Rotation",
        "ambModelInfo": "AMB Model Info",
        "ambChildModelInfo": "AMB Child Model Info",
        "ambModelSmf": "Model (smf)",
        "ambChildModelSmf": "Child Model (smf)[{0}]",
        "ambModelPosX": "X Distance",
        "ambModelPosY": "Y Distance",
        "ambModelPosZ": "Z Distance",
        "ambModelDirX": "X Direction",
        "ambModelDirY": "Y Direction",
        "ambModelDirZ": "Z Direction",
        "ambModelRotX": "X-Axis Rotation",
        "ambModelRotY": "Y-Axis Rotation",
        "ambModelRotZ": "Z-Axis Rotation",
        "ambModelPer": "per",
        "trainPosStopBtnLabel": "Stop Tracking",
        "saveBtnLabel": "Save",
        "modifyBtnLabel": "Change",
        "contents": "Contents",
    },
    "smf": {
        "fileType": "SELENE MODEL",
        "fileListType": "SELENE MODEL List",
        "smfVersion": "SMF Version: {0}",
        "meshNum": "Mesh Count: {0}",
        "frameNum": "Frame Count: {0}",
        "animeNum": "Animation Count: {0}",
        "frameNumFormat": "Frame No.{0}/{1}",
        "frameMatrixLabel": "Frame Transform Matrix",
        "frameName": "Frame Name",
        "frameMeshIndex": "Index of Owned Mesh",
        "parentFrameIndex": "Parent Frame Index",
        "vCenterLabel": "Center Coordinates {0}",
        "vAxisLabel": "Local XYZ Axes {0}",
        "fLengthLabel": "XYZ Axis Length {0}",
        "anisNumFormat": "Anis No.{0}/{1}",
        "anisName": "Animation Name",
        "anisCount": "Animation Data Count",
        "anisTime": "Animation Final Time",
        "aniNumFormat": "{0}({1}/{2})",
        "anisTargetFrameIndex": "Target Frame Index to Apply ({0})",
        "meshNumFormat": "Mesh No.{0}/{1}",
        "meshName": "Mesh Name",
        "meshMtrlNum": "Number of Owned Materials",
        "boneLocalMatrix": "Bone Local Offset Matrix",
        "boneFrameIndex": "Target Frame Index of Bone",
        "vPCLabel": "Vertex Position {0}",
        "vPCColor": "Vertex Color",
        "vNLabel": "Vertex Normal {0}",
        "vBLabel": "Vertex Tangent {0}",
        "uvLabel": "Vertex Texture UV",
        "lightMapUvLabel": "Vertex Lightmap Texture UV",
        "idxLabel": "Vertex Index",
        "colStart": "Face Start Position",
        "colCount": "Face Count",
        "colAttribute": "Face Attribute",
        "colIndexList": "Vertex Indices Making Up Face",
        "plainLabel": "Face Data",
        "vxLabel": "Vertex Position",
        "vxColor": "Vertex Color",
        "vxNLabel": "Vertex Normal",
        "mtrlName": "Material Name",
        "polyStart": "Polygon Start Position",
        "polyCount": "Polygon Count",
        "mtrlPStart": "Vertex Start Position",
        "mtrlPCount": "Vertex Count",
        "texCommon": "Texture Name Chunk (Normal)",
        "texLight": "Texture Name Chunk (Lightmap)",
        "texDds": "Texture Name Chunk (DDS)",
        "texSpe": "Texture Name Chunk (Specular)",
        "texN": "Texture Name Chunk (Normal Map)",
        "mtrlDraw": "Material Draw Attributes",
        "zTest": "Z Test",
        "zWrite": "Z Write",
        "alphaTest": "Alpha Test",
        "alphaBND": "Alpha Test (Threshold)",
        "cull": "Backface Culling",
        "lgt": "Lighting",
        "diffLabel": "Diffuse Color",
        "emisLabel": "Emissive Color",
        "speColor": "Specular Color",
        "refractive": "Reflectivity (higher = stronger reflection)",
        "roughly": "Roughness (higher = softer reflection)",
        "bump": "Parallax for Parallax Map",
        "locationParentFrame": "Destination Parent Frame",
        "swapToModelMeshNoLabel": "Number of Mesh to Swap With",
        "treeMeshNumFormat": "(Mesh No.{0})",
        "smfFile": "File",
        "glbFile": "glb File",
        "fbxFile": "fbx File",
        "xFile": "x File",
        "csvFile": "csv File",
        "swapFrame": "Swap Frame",
        "editInfoFrame": "Modify Frame Info",
        "swapMesh": "Swap Mesh",
        "scriptLabel": "Structure",
        "createStandardLabel": "Create RS Standard Gauge",
        "swapFrameLabel": "Swap Frame Position",
        "editInfoFrameLabel": "Modify Frame Info",
        "deleteFrameLabel": "Delete Frame",
        "copyAndPasteFrameLabel": "Copy and Paste Selected Frame",
        "extract3dLabel": "Export SMF as Another 3D File",
        "turnModelMeshLabel": "Rotate Selected Mesh 180 Degrees",
        "swapModelMeshLabel": "Swap Selected Mesh",
        "meshMaterialCsvSaveLabel": "Extract Materials as CSV",
        "meshMaterialCsvLoadLabel": "Overwrite Materials from CSV",
        "scanSmfImageLabel": "Search Image Files in SMF File List",
        "copyImageLabel": "Specify Folder to Copy Image Files to Above Path",
        "framePosInfoLabel": "Frame Coordinate Info (x, y, z)",
        "frameRotInfoLabel": "Frame Rotation Info (x, y, z)",
        "errorList": {
            "E1": "index exceeds file size",
            "E2": "Chunk name parse error (index: 0x{0:02x})",
            "E3": "Last chunk name read ({0}) (index: 0x{1:02x})",
            "E4": "Length mismatch for chunk {0} (index: 0x{1:02x}) (configured: {2}, actual: {3})"
        }
    },
    "ssUnity": {
        "csvNotchNum": "Number of Notches",
        "csvOrgNum": "Number of Train Sets",
        "csvBodyClass": "bodyClass",
        "csvBodyModel": "body Model",
        "csvPantaModel": "panta Model",
        "csvBodyClassIndexList": "bodyClass Index List",
        "csvBodyModelIndexList": "body Model Index List",
        "csvPantaModelIndexList": "panta Model Index List",
        "headerNum": "No.",
        "headerPathId": "PathId",
        "headerName": "Name",
        "headerKind": "Kind",
        "headerSize": "Size",
        "extractFile": "Extract File",
        "saveFile": "Overwrite File",
        "extractCsv": "Extract as CSV",
        "saveCsv": "Overwrite from CSV",
        "loadSaveFileLabel": "File",
        "loadSaveFileExcelLabel": "Excel File",
        "selectNum": "Selected Row Number: ",
        "editDenFile": "Modify den File",
        "editResourcesAssets": "Modify resources.assets",
        "extractFileLabel": "Extract File",
        "saveFileLabel": "Overwrite File",
        "saveResourcesAssets": "Save resources.assets",
        "scriptLabel": "File Contents",
        "ssStageDataTabList": [
            "Story/Placement Info", "Line-Specific Image Data", "Image Settings Info",
            "Station Names", "CPU Switching", "Comic Script",
            "Rain Events", "Dosan Line Special",
            "Model Info", "Rail Info", "Pri Info", "AMB Info",
        ],
        "searchText": "Search"
    },
    "infoList": {
        "I1": "Are you sure you want to modify as-is?",
        "I2": "Are you sure you want to insert as-is?",
        "I3": "Script has been modified",
        "I4": "Please select an insert position",
        "I5": "Pasted",
        "I6": "This will delete item {0}.\nAre you sure?",
        "I7": "Modify header info?",
        "I8": "Header info modified",
        "I9": "This will delete the selected row.\nAre you sure?",
        "I10": "Extracted as CSV",
        "I11": "This will overwrite from the selected CSV.\nAre you sure?",
        "I12": "Copied",
        "I13": "Ready to convert.\nExisting files will be overwritten.\nAre you sure?",
        "I14": "All lists have been written",
        "I15": "Loaded {0} rows of data.\nOverwrite?",
        "I16": "Overwritten from CSV",
        "I17": "* The above param is saved as a string\n\n",
        "I18": "Change the count of section {0} to",
        "I19": " and modify",
        "I20": "The set value is lower than the current value\n",
        "I21": "Modify with this value?",
        "I22": "Number of sections modified",
        "I23": "Section contents modified",
        "I24": "Change list count to",
        "I25": "This will delete item {0}.\nAre you sure?",
        "I26": "Model element info modified",
        "I27": "Please enter a value",
        "I28": "Modify image info?",
        "I29": "Image info modified",
        "I30": "[Warning!] There is a duplicate element ({0}-{1})\n",
        "I31": "Modify model element info?",
        "I32": "Insert model element info?",
        "I33": "smf element info modified",
        "I34": "Modify smf element info?",
        "I35": "Modify bin file and flag info?",
        "I36": "bin file and flag info modified",
        "I37": "Please select the element to copy.\nThe copied element will be added at the end",
        "I38": "Copy {0}?",
        "I39": "Are you sure you want to swap as-is?",
        "I40": "This will swap No.{0} and No.{1}.\n",
        "I41": "BGM modified",
        "I42": "Modify stage info?",
        "I43": "Stage settings modified",
        "I44": "Please enter a value",
        "I45": "* This will revert {0}'s notch info to {1} notches.\n",
        "I46": "\nRevert all the way back to default?",
        "I47": "Data reverted",
        "I48": "Extracted as text",
        "I49": "Train info modified",
        "I50": "This will overwrite the den file.\nAre you sure?\n(Overwriting may fail due to permission issues)",
        "I51": "den file overwritten",
        "I52": "All trains will be changed by the same rate and saved immediately.\nAre you sure?",
        "I53": "All trains will be changed to the same value and saved immediately.\nAre you sure?",
        "I54": "All trains modified",
        "I55": "Number of train sets modified",
        "I56": "Number of colors modified",
        "I57": "Please modify the notch info",
        "I58": "Modify notch info?",
        "I59": "Number of notches changed",
        "I60": "Modify with this info?",
        "I61": "Info modified",
        "I62": "This will delete item {1} of {0}.\nAre you sure?",
        "I63": "Modify model info?",
        "I64": "Model info modified",
        "I65": "Number of lens entries modified",
        "I66": "Lens info modified",
        "I67": "Number of tail entries modified",
        "I68": "Tail info modified",
        "I69": "BGM info modified",
        "I70": "Modify with this list?",
        "I71": "Insert with this value?",
        "I72": "Car count info modified",
        "I73": "Number of ANIME modified",
        "I74": "ANIME info modified",
        "I75": "else1 info modified",
        "I76": " modified",
        "I77": "Number of station signs modified",
        "I78": "Station sign info modified",
        "I79": "smf info modified",
        "I80": "List modified",
        "I81": "Station name position info modified",
        "I82": "Number of else2 modified",
        "I83": "else2 info modified",
        "I84": "CPU info modified",
        "I85": "Comic Script modified",
        "I86": "Number of Dosan Line entries modified",
        "I87": "Dosan Line info modified",
        "I88": "Rail info modified",
        "I89": "Return rail data auto-generated.\n(Fine branch adjustments still need to be made in Rail Info)",
        "I90": "RS port file created.",
        "I91": "Number of {0} modified",
        "I92": "{0} info modified",
        "I93": "Number of else4 modified",
        "I94": "else4 info modified",
        "I95": "AMB info modified",
        "I96": "A rail CSV already exists.\nOverwrite?\n(Overwriting may fail due to permission issues)",
        "I97": "An AMB CSV already exists.\nOverwrite?\n(Overwriting may fail due to permission issues)",
        "I98": "Change the memory info for rail {0}?\nPressing No cancels the change and switches to search mode.\n(Overwriting may fail due to permission issues)",
        "I99": "Memory info for rail {0} changed.",
        "I100": "Change the memory info for AMB {0}?\nPressing No cancels the change and switches to search mode.\n(Overwriting may fail due to permission issues)",
        "I101": "Memory info for AMB {0} changed.",
        "I102": "Are you sure you want to move as-is?",
        "I103": "This will move {0} under {1}.\nThis affects all child elements of this element.\n",
        "I104": "SMF modified",
        "I105": "Only the following models can do this",
        "I106": "Please load {0}",
        "I107": "The models don't match",
        "I108": "Standard gauge created",
        "I109": "This will delete {0}.\nThis affects all child elements of this element.\nAre you sure you want to delete it?",
        "I110": "Extracted as binary",
        "I111": "Overwritten from CSV\nPress the Save button to create 【resources_new.assets】",
        "I112": "resources_new.assets created.",
        "I113": "Extracted to Excel.",
        "I114": "Overwritten from Excel.",
        "I115": "Rail No.{0} uses a duplicate model name\n\"{1}\".\nIs this OK?",
        "I116": "AMB No.{0} uses a duplicate model name\n\"{1}\".\nIs this OK?",
        "I117": "Loaded data from Excel.\nOverwrite?",
        "I118": "Copy operation complete",
        "I119": "Modify type info?",
        "I120": "Type info modified",
        "I121": "Extracted as glb",
        "I122": "Extracted as x",
        "I123": "Extracted as fbx",
        "I124": "Rotate the selected mesh 180 degrees?\nThis will overwrite if rotated",
        "I125": "Rotated",
        "I126": "Are you sure you want to swap as-is?",
        "I127": "This will copy and paste {0}.\nThis affects all child elements of this element.\nAre you sure you want to copy and paste it as-is?",
        "I128": "Copied and pasted",
        "I129": "This will change the following detail elements for mesh number {0}\n{1}\nIs this OK?",
        "I130": "Are you sure you want to modify the frame info as-is?",
        "I131": "Frame info modified",
        "I132": "The specified mesh number ({0}) already exists\nThis may cause issues, but",
        "I133": "Deleting the mesh number ({0}) specified in the frame\nwill also delete the mesh info\n",
        "I134": "An empty mesh number ({0}) will be created.\n",
        "I135": "Changing existing mesh number ({0}) to ({1}).\nThis may cause reference issues, but",
        "I136": "Overwrite materials?",
        "I137": "Materials overwritten",
        "I138": "Textures without a TEXC element will be ignored.\n",
        "I139": "Initial station display No info modified",
        "I140": "Duplicate, so assigned to provisional rail number ({0})",
        "I141": "List count modified",
    },
    "modify": "Modify",
    "insert": "Insert",
    "delete": "Delete",
    "error": "Error",
    "intError": "Integer Error",
    "numberError": "Number Error",
    "saveError": "Save Error",
    "valueError": "Value Error",
    "readError": "Read Error",
    "warning": "Warning",
    "confirm": "Confirm",
    "success": "Success",
    "errorList": {
        "E1": "Please select a program",
        "E2": "Undefined command number ({0}). Aborting load.",
        "E3": "Please enter a number.",
        "E4": "Save failed.\nThe file may be open in another program\nor there may be a permission issue",
        "E5": "There are invalid values",
        "E6": "An unexpected error occurred.\nThis may not be a Densha de D comic script, or the file may be corrupted.",
        "E7": "The extract-as-CSV feature failed.\nThere may be a permission issue.",
        "E8": "The command [{1}] on line {0} is\nnot a valid command",
        "E9": "Line {0}'s command contains an element [{1}] that can't be converted to a number",
        "E10": "There is a duplicate FVT number [ {0} ]",
        "E11": "Line {0} contains an element that can't be converted to a number",
        "E12": "The text on line {0} can't be converted to Shift-JIS",
        "E13": "Please select a game",
        "E14": "Unexpected error.",
        "E15": "Failed to load data on line {0}.",
        "E16": "Header mismatch",
        "E17": "The smf name is an empty string",
        "E18": "An unexpected error occurred.\nThis may not be a Densha de D MDLINFO, or the file may be corrupted.",
        "E19": "An unexpected error occurred.\nThis may not be a Densha de D SMF, or the file may be corrupted.",
        "E20": "The string is too long.",
        "E21": "An unexpected error occurred.\nThis may not be a Densha de D file, or the file may be corrupted.",
        "E22": "Could not find notch info",
        "E23": "{0} notch is not supported",
        "E24": "Notch header is missing",
        "E25": "Loading {0} notch\nFailed to load {1} notch info",
        "E26": "Could not find performance info",
        "E27": "Could not find bogie model info",
        "E28": "Could not find train set count info",
        "E29": "Train set count is less than 1",
        "E30": "Could not find car model info",
        "E31": "Could not find COL model info",
        "E32": "Could not find pantograph model info",
        "E33": "Could not find pantograph index info",
        "E34": "Pantograph index info is invalid",
        "E35": "Failed to load pantograph index info",
        "E36": "Could not find attribute index info",
        "E37": "Could not find lens flare info",
        "E38": "Could not find tail lamp info",
        "E39": "Failed to load line {0}",
        "E40": "Train set count is less than 2",
        "E41": "Could not find car index info",
        "E42": "Car index info is invalid",
        "E43": "Failed to load car index info",
        "E44": "Could not find model index 2 info",
        "E45": "Could not find color count info",
        "E46": "Could not find color/model count info",
        "E47": "Number of bogie models is less than 2",
        "E48": "Could not find COL_index info",
        "E49": "COL_index info is invalid",
        "E50": "Failed to load COL_index info",
        "E51": "Train {0} does not exist",
        "E52": "Could not find {0}",
        "E53": "Could not load notch row (line {0})",
        "E54": "Could not load performance row (line {0})",
        "E55": "Could not load rain performance row (line {0})",
        "E56": "Could not load curve performance row (line {0})",
        "E57": "Could not load other row (line {0})",
        "E58": "Could not load tilt performance row (line {0})",
        "E59": "Could not load one-wheel running row (line {0})",
        "E60": "Please enter an integer.",
        "E61": "Please enter an integer of {0} or greater.",
        "E62": "Please select an item",
        "E63": "The extract-as-CSV feature failed.\nThere may be a permission issue.",
        "E64": "The extract-as-text feature failed.\nThere may be a permission issue.",
        "E65": "LS does not support color count modification",
        "E66": "Please make BS color modifications via CSV",
        "E67": "There must be at least {0} bogie models",
        "E68": "Cannot assign \"index {1}\" for {0}",
        "E69": "There is no function to change this",
        "E70": "This rail does not exist",
        "E71": "Overwrite from CSV failed.\nThere may be a permission issue.",
        "E72": "Failed to create RS port file.\nThere may be a permission issue.",
        "E73": "This AMB does not exist",
        "E74": "Load failed.",
        "E75": "There is no child data on the last row",
        "E76": "This is not {0}'s rail data",
        "E77": "Could not find the game.",
        "E78": "Cannot access the game's memory\nPlease run as administrator",
        "E79": "Cannot access the rail's memory.\nPlease select a stage first, then run",
        "E80": "Save failed. Cannot access the rail's memory.",
        "E81": "Cannot access the AMB's memory.\nPlease select a stage first, then run",
        "E82": "Save failed. Cannot access the AMB's memory.",
        "E83": "bodyClass index info is invalid",
        "E84": "body model index info is invalid",
        "E85": "panta model index info is invalid",
        "E86": "Number of bodyClass indices does not match the train set count",
        "E87": "Number of body model indices does not match the train set count",
        "E88": "Number of panta model indices does not match the train set count",
        "E89": "The extract-as-binary feature failed.\nThere may be a permission issue.",
        "E90": "AudioClip is not supported",
        "E91": "UnityPy is not installed.\nPlease install it via setup.bat",
        "E92": "Error loading line {0}!\nThe number of else3 child data does not match the count",
        "E93": "The list must have at least {0} entries",
        "E94": "The extract-as-Excel feature failed.\nThere may be a permission issue.",
        "E95": "Sheet name \"{0}\" does not exist.",
        "E96": "Model \"{1}\" of No.{0} does not exist",
        "E97": "Element 4's element is missing for Rail No.{0}",
        "E98": "This text file has the wrong format.\n{0}",
        "E99": "No rail data version in the \"BGM/Placement Info\" sheet",
        "E100": "No label for {1} in sheet \"{0}\"",
        "E101": "Read error on row {1} in sheet \"{0}\"",
        "E102": "Aborting overwrite of rail data.",
        "E103": "The Excel file does not exist: ",
        "E104": "The den file does not exist: ",
        "E105": "The den file is not stagedata: ",
        "E106": "\"{0}\" is missing in stagedata",
        "E107": "\"{0}\" is missing in Excel",
        "E108": "Read error for \"{0}\" in Excel",
        "E109": "Rail data model name \"{0}\" does not exist",
        "E110": "AMB data model name \"{0}\" does not exist",
        "E111": "While reading \"{0}\" in Excel, the data for \"{1}\" is blank",
        "E112": "The configured data count ({1}) for \"{0}\" in stagedata\nis greater than the actual data count ({2})",
        "E113": "No.{0}'s 【AMB count data】 is 0 or less",
        "E114": "Read error for \"{0}\" in stagedata\n(No.{1}'s data = 【{2}】)",
        "E115": "train_org_data is an old version",
        "E116": "Missing count (data) for \"{0}\"",
        "E117": "Count (data) for \"{0}\" is abnormal\n(data = 【{1}】)",
        "E118": "There were some errors in stagedata.\nSee {0} for details",
        "E119": "There is unused AMB info at AMB No.{0}",
        "E120": "\"{1}\" at AMB No.{0} is a model that cannot be used as an AMB",
        "E121": "\"{1}\" at Rail No.{0} is a model that cannot be used as a rail",
        "E122": "\"{1}\" at Rail No.{0} is {2}, but {3} is specified",
        "E123": "The selected mesh face is not triangular",
        "E124": "File read error\nThe file may not be in Shift-JIS format",
        "E125": "The number of loaded materials ({0}) does not match the original count ({1})",
        "E126": "Material No.{0} is missing a texture name",
        "E127": "Material No.{0}'s texture name is too long",
        "E128": "Unexpected error while creating return data for Rail No.{0}",
        "E129": "While reading \"{0}\" in Excel, [{1}] is not hexadecimal [0x] (data = 【{2}】)",
        "E130": "While reading \"{0}\" in Excel, [{1}] is hexadecimal [0x] (data = 【{2}】)",
        "E131": "The entered rail number ({0}) already exists",
        "E132": "The entered rail number ({0}) already exists\nAre you sure?",
        "E133": "All rail numbers usable for inserting before are already in use",
        "E134": "Failed to create return rail data.",
        "E135": "Unexpected error while reading {1} in sheet \"{0}\"",
        "E136": "The model and COL counts do not match",
        "E137": "{0} info is missing",
        "E138": "The SMF frame name is empty",
        "E139": "{0} is empty",
        "E140": "This version cannot save strings",
        "E141": "This does not match {0}'s command spec",
        "E142": "The command count for section {0},{1} has reached its limit",
        "E143": "There is a duplicate section ({0},{1})",
        "E144": "Cannot change existing mesh number ({0}) to a different number ({1})",
        "E145": "This is not a recognized executable file",
    },
    "excel": {
        "errorColor": "FF0000",
        "warningColor": "FFFF00",
        "disableColor": "CCCCCC"
    },
    "menu": {
        "program": {
            "name": "Mod Programs",
            "SSUnity": "SS Mod",
            "orgInfoEditor": "Train Performance",
            "mdlBin": "Model Binary",
            "mdlinfo": "MDLINFO",
            "comicscript": "Comic Script",
            "musicEditor": "BGM List",
            "fvtMaker": "FVT Creator",
            "railEditor": "Rail Editor",
            "rsRail": "RS Rail/AMB",
            "smf": "SMF",
            "exit": "Exit",
        },
        "file": {
            "name": "File",
            "loadFile": "Open File",
        },
        "csv": {
            "name": "CSV Options",
            "rail": {
                "opt1": "Always Confirm Rail CSV",
                "opt2": "Always Overwrite Rail CSV",
                "opt3": "Never Overwrite Rail CSV",
            },
            "amb": {
                "opt1": "Always Confirm AMB CSV",
                "opt2": "Always Overwrite AMB CSV",
                "opt3": "Never Overwrite AMB CSV",
            }
        },
        "comicscript": {
            "gameList": ["SS", "RS", "CS", "BS", "LS"],
            "name": "Game to Load Script For"
        },
        "smf": {
            "name": "SMF Write Options",
            "write": {
                "opt1": "Write FRM",
                "opt2": "Write MESH",
                "opt3": "Write MESH Detail Sections",
                "opt4": "Write MTRL",
            },
            "glb": {
                "opt1": "Reference Textures When Writing glb",
                "opt2": "Embed Textures When Writing glb"
            }
        },
        "SSUnity": {
            "name": "xlsx Read/Write Options",
            "write": {
                "model1": "Output Models by Name",
                "model2": "Output Models by Index",
                "flag1": "Flags as Decimal",
                "flag2": "Flags as Hexadecimal",
                "ambRead1": "AMB Info Line-Broken",
                "ambRead2": "AMB Info as Single Line",
            }
        },
        "appearance": {
            "rootFrame": "Appearance Settings",
        }
    },
    "appearance": {
        "updateConfirm": "Apply this configuration?",
        "success": "Colors updated as configured",
        "rootFrame": {
            "editRootFrameTitle": "Change Appearance",
            "windowsDialogLabel": "Windows Dialogs",
            "lightModeRadioLabel": "Light Mode",
            "darkModeRadioLabel": "Dark Mode",
            "tkThemeNameLabel": "Theme",
            "rootFrameLabel": "Main",
            "bgColorLabel": "Background Color",
            "fgColorLabel": "Text Color",
            "labelLabel": "Label",
            "labelFrameLabel": "Label Frame",
            "radiobuttonLabel": "Radio Button",
            "treeviewLabel": "Table Item",
            "selectedBgColorLabel": "Selected\nBackground Color",
            "selectedFgColorLabel": "Selected\nText Color",
            "colorEditButtonLabel": "Change Color",
            "colorDefaultButtonLabel": "Set to Default Color",
            "askColorSetDefault": "Set to default color?",
            "buttonLabel": "Button (*Background color depends on theme)",
            "entryLabel": "Entry Field (*Background color depends on theme)",
            "treeviewThemeLabel": "Table (*Theme-dependent elements)",
            "treeviewFieldBgLabel": "Outer\nBackground Color",
            "treeviewHeaderBgLabel": "Header\nBackground Color",
            "treeviewHeaderFgLabel": "Header\nText Color",
            "comboboxLabel": "Combo Box (*Theme-dependent)\nDropdown applies after restart",
            "radioThemeLabel": "Radio Button (*Theme-dependent)",
            "radioButtonColorLabel": "Button Color",
            "radioButtonSelColorLabel": "Selected\nButton Color",
        }
    },
    "update": {
        "title": "Version (checked once)",
        "message": "A new version {0} is available.\nOpen the download page?"
    },
    "app": {
        "title": "Densha de D Mod Integrated Edition {0}"
    }
}
